# docker-compose.yml

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGO_URI}
      - MONGO_URI_PUBLIC=${MONGO_URI_PUBLIC}
      - JWT_SECRET=${JWT_SECRET}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis


  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - '6379:6379'

  client: # This is your admin panel
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server

  portal: # This is your client portal
    build:
      context: .
      dockerfile: Dockerfile.portal
    depends_on:
      - server

  public-website: # New service for the public website
    build:
      context: .
      dockerfile: Dockerfile.public-website
    depends_on:
      - server

  nginx:
    image: nginx:stable-alpine
    container_name: reverse_proxy
    ports:
      - '5000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
      - portal
      - server
      - public-website # Add the new service here